### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by bellafiga** [IlluzionzDev/CustomFishing#4]
Everytime i restart the Server, every Rewards Permission change.
From:
` Permission: customfishing.default`
to
` Permission: customfishing.customfishing.customfishing.customfishing.customfishing.default`

I also tryed to put:
`Permission: customfishing.user`

**Comment by IlluzionzDev** [comment]
I found the problem, working on a fix now that will be deployed hopefully later today

**Comment by IlluzionzDev** [comment]
Deployed in version 4.0.1
