### ISSUE TITLE
paper 1.16.5

### ISSUE THREAD

**Issue by JoJesseGaming** [IlluzionzDev/CustomFishing#5]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.illuzionzstudios.customfishing.mist.scheduler.MinecraftScheduler$SynchronizationService (file:/home/container/plugins/CustomFishing-4.1.3.jar) to method java.lang.Enum.finalize()
WARNING: Please consider reporting this to the maintainers of com.illuzionzstudios.customfishing.mist.scheduler.MinecraftScheduler$SynchronizationService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by taljafox** [comment]
Yup same thing

**Comment by IlluzionzDev** [comment]
Has been solved
